[phases.setup]
nixPkgs = [
  "nodejs_20",
  "python312",
  "python312Packages.pip",
  "python312Packages.setuptools",
  "gcc",
  "gnumake",
  "pkg-config"
]

[phases.build]
cmds = [
  "npm install --build-from-source"
]

[start]
cmd = "node server.js"
